// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package openmeteo

import "strconv"

type Probability byte

const (
	Probabilitynone       Probability = 0
	Probabilitygt0        Probability = 1
	Probabilitygt0p1      Probability = 2
	Probabilitygt1        Probability = 3
	Probabilitygt2        Probability = 4
	Probabilitygt3        Probability = 5
	Probabilitygt4        Probability = 6
	Probabilitygt5        Probability = 7
	Probabilitygt8        Probability = 8
	Probabilitygt10       Probability = 9
	Probabilitygt15       Probability = 10
	Probabilitygt20       Probability = 11
	Probabilitygt25       Probability = 12
	Probabilitygt30       Probability = 13
	Probabilitygt35       Probability = 14
	Probabilitygt40       Probability = 15
	Probabilitygt50       Probability = 16
	Probabilitygt60       Probability = 17
	Probabilitygt75       Probability = 18
	Probabilitygt80       Probability = 19
	Probabilitygt100      Probability = 20
	Probabilitylt0        Probability = 21
	Probabilitylt0p1      Probability = 22
	Probabilitylt1        Probability = 23
	Probabilityltm1       Probability = 24
	Probabilityltm2       Probability = 25
	Probabilityltm3       Probability = 26
	Probabilityltm4       Probability = 27
	Probabilityltm5       Probability = 28
	Probabilityltm8       Probability = 29
	Probabilityltm10      Probability = 30
	Probabilityltm15      Probability = 31
	Probabilityltm20      Probability = 32
	Probabilitygt1stdev   Probability = 33
	Probabilitygt1p5stdev Probability = 34
	Probabilitygt2stdev   Probability = 35
	Probabilitylt1stdev   Probability = 36
	Probabilitylt1p5stdev Probability = 37
	Probabilitylt2stdev   Probability = 38
)

var EnumNamesProbability = map[Probability]string{
	Probabilitynone:       "none",
	Probabilitygt0:        "gt0",
	Probabilitygt0p1:      "gt0p1",
	Probabilitygt1:        "gt1",
	Probabilitygt2:        "gt2",
	Probabilitygt3:        "gt3",
	Probabilitygt4:        "gt4",
	Probabilitygt5:        "gt5",
	Probabilitygt8:        "gt8",
	Probabilitygt10:       "gt10",
	Probabilitygt15:       "gt15",
	Probabilitygt20:       "gt20",
	Probabilitygt25:       "gt25",
	Probabilitygt30:       "gt30",
	Probabilitygt35:       "gt35",
	Probabilitygt40:       "gt40",
	Probabilitygt50:       "gt50",
	Probabilitygt60:       "gt60",
	Probabilitygt75:       "gt75",
	Probabilitygt80:       "gt80",
	Probabilitygt100:      "gt100",
	Probabilitylt0:        "lt0",
	Probabilitylt0p1:      "lt0p1",
	Probabilitylt1:        "lt1",
	Probabilityltm1:       "ltm1",
	Probabilityltm2:       "ltm2",
	Probabilityltm3:       "ltm3",
	Probabilityltm4:       "ltm4",
	Probabilityltm5:       "ltm5",
	Probabilityltm8:       "ltm8",
	Probabilityltm10:      "ltm10",
	Probabilityltm15:      "ltm15",
	Probabilityltm20:      "ltm20",
	Probabilitygt1stdev:   "gt1stdev",
	Probabilitygt1p5stdev: "gt1p5stdev",
	Probabilitygt2stdev:   "gt2stdev",
	Probabilitylt1stdev:   "lt1stdev",
	Probabilitylt1p5stdev: "lt1p5stdev",
	Probabilitylt2stdev:   "lt2stdev",
}

var EnumValuesProbability = map[string]Probability{
	"none":       Probabilitynone,
	"gt0":        Probabilitygt0,
	"gt0p1":      Probabilitygt0p1,
	"gt1":        Probabilitygt1,
	"gt2":        Probabilitygt2,
	"gt3":        Probabilitygt3,
	"gt4":        Probabilitygt4,
	"gt5":        Probabilitygt5,
	"gt8":        Probabilitygt8,
	"gt10":       Probabilitygt10,
	"gt15":       Probabilitygt15,
	"gt20":       Probabilitygt20,
	"gt25":       Probabilitygt25,
	"gt30":       Probabilitygt30,
	"gt35":       Probabilitygt35,
	"gt40":       Probabilitygt40,
	"gt50":       Probabilitygt50,
	"gt60":       Probabilitygt60,
	"gt75":       Probabilitygt75,
	"gt80":       Probabilitygt80,
	"gt100":      Probabilitygt100,
	"lt0":        Probabilitylt0,
	"lt0p1":      Probabilitylt0p1,
	"lt1":        Probabilitylt1,
	"ltm1":       Probabilityltm1,
	"ltm2":       Probabilityltm2,
	"ltm3":       Probabilityltm3,
	"ltm4":       Probabilityltm4,
	"ltm5":       Probabilityltm5,
	"ltm8":       Probabilityltm8,
	"ltm10":      Probabilityltm10,
	"ltm15":      Probabilityltm15,
	"ltm20":      Probabilityltm20,
	"gt1stdev":   Probabilitygt1stdev,
	"gt1p5stdev": Probabilitygt1p5stdev,
	"gt2stdev":   Probabilitygt2stdev,
	"lt1stdev":   Probabilitylt1stdev,
	"lt1p5stdev": Probabilitylt1p5stdev,
	"lt2stdev":   Probabilitylt2stdev,
}

func (v Probability) String() string {
	if s, ok := EnumNamesProbability[v]; ok {
		return s
	}
	return "Probability(" + strconv.FormatInt(int64(v), 10) + ")"
}
