// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package openmeteo

import "strconv"

type Model byte

const (
	Modelundefined                             Model = 0
	Modelbest_match                            Model = 1
	Modelgfs_seamless                          Model = 2
	Modelgfs_global                            Model = 3
	Modelgfs_hrrr                              Model = 4
	Modelmeteofrance_seamless                  Model = 5
	Modelmeteofrance_arpege_seamless           Model = 6
	Modelmeteofrance_arpege_world              Model = 7
	Modelmeteofrance_arpege_europe             Model = 8
	Modelmeteofrance_arome_seamless            Model = 9
	Modelmeteofrance_arome_france              Model = 10
	Modelmeteofrance_arome_france_hd           Model = 11
	Modeljma_seamless                          Model = 12
	Modeljma_msm                               Model = 13
	Modeljms_gsm                               Model = 14
	Modeljma_gsm                               Model = 15
	Modelgem_seamless                          Model = 16
	Modelgem_global                            Model = 17
	Modelgem_regional                          Model = 18
	Modelgem_hrdps_continental                 Model = 19
	Modelicon_seamless                         Model = 20
	Modelicon_global                           Model = 21
	Modelicon_eu                               Model = 22
	Modelicon_d2                               Model = 23
	Modelecmwf_ifs04                           Model = 24
	Modelmetno_nordic                          Model = 25
	Modelera5_seamless                         Model = 26
	Modelera5                                  Model = 27
	Modelcerra                                 Model = 28
	Modelera5_land                             Model = 29
	Modelecmwf_ifs                             Model = 30
	Modelgwam                                  Model = 31
	Modelewam                                  Model = 32
	Modelglofas_seamless_v3                    Model = 33
	Modelglofas_forecast_v3                    Model = 34
	Modelglofas_consolidated_v3                Model = 35
	Modelglofas_seamless_v4                    Model = 36
	Modelglofas_forecast_v4                    Model = 37
	Modelglofas_consolidated_v4                Model = 38
	Modelgfs025                                Model = 39
	Modelgfs05                                 Model = 40
	ModelCMCC_CM2_VHR4                         Model = 41
	ModelFGOALS_f3_H_highresSST                Model = 42
	ModelFGOALS_f3_H                           Model = 43
	ModelHiRAM_SIT_HR                          Model = 44
	ModelMRI_AGCM3_2_S                         Model = 45
	ModelEC_Earth3P_HR                         Model = 46
	ModelMPI_ESM1_2_XR                         Model = 47
	ModelNICAM16_8S                            Model = 48
	Modelcams_europe                           Model = 49
	Modelcams_global                           Model = 50
	Modelcfsv2                                 Model = 51
	Modelera5_ocean                            Model = 52
	Modelcma_grapes_global                     Model = 53
	Modelbom_access_global                     Model = 54
	Modelbom_access_global_ensemble            Model = 55
	Modelarpae_cosmo_seamless                  Model = 56
	Modelarpae_cosmo_2i                        Model = 57
	Modelarpae_cosmo_2i_ruc                    Model = 58
	Modelarpae_cosmo_5m                        Model = 59
	Modelecmwf_ifs025                          Model = 60
	Modelecmwf_aifs025                         Model = 61
	Modelgfs013                                Model = 62
	Modelgfs_graphcast025                      Model = 63
	Modelecmwf_wam025                          Model = 64
	Modelmeteofrance_wave                      Model = 65
	Modelmeteofrance_currents                  Model = 66
	Modelecmwf_wam025_ensemble                 Model = 67
	Modelncep_gfswave025                       Model = 68
	Modelncep_gefswave025                      Model = 69
	Modelknmi_seamless                         Model = 70
	Modelknmi_harmonie_arome_europe            Model = 71
	Modelknmi_harmonie_arome_netherlands       Model = 72
	Modeldmi_seamless                          Model = 73
	Modeldmi_harmonie_arome_europe             Model = 74
	Modelmetno_seamless                        Model = 75
	Modelera5_ensemble                         Model = 76
	Modelecmwf_ifs_analysis                    Model = 77
	Modelecmwf_ifs_long_window                 Model = 78
	Modelecmwf_ifs_analysis_long_window        Model = 79
	Modelukmo_global_deterministic_10km        Model = 80
	Modelukmo_uk_deterministic_2km             Model = 81
	Modelukmo_seamless                         Model = 82
	Modelncep_gfswave016                       Model = 83
	Modelncep_nbm_conus                        Model = 84
	Modelukmo_global_ensemble_20km             Model = 85
	Modelecmwf_aifs025_single                  Model = 86
	Modeljma_jaxa_himawari                     Model = 87
	Modeleumetsat_sarah3                       Model = 88
	Modeleumetsat_lsa_saf_msg                  Model = 89
	Modeleumetsat_lsa_saf_iodc                 Model = 90
	Modelsatellite_radiation_seamless          Model = 91
	Modelkma_gdps                              Model = 92
	Modelkma_ldps                              Model = 93
	Modelkma_seamless                          Model = 94
	Modelitalia_meteo_arpae_icon_2i            Model = 95
	Modelukmo_uk_ensemble_2km                  Model = 96
	Modelmeteofrance_arome_france_hd_15min     Model = 97
	Modelmeteofrance_arome_france_15min        Model = 98
	Modelmeteoswiss_icon_ch1                   Model = 99
	Modelmeteoswiss_icon_ch2                   Model = 100
	Modelmeteoswiss_icon_ch1_ensemble          Model = 101
	Modelmeteoswiss_icon_ch2_ensemble          Model = 102
	Modelmeteoswiss_icon_seamless              Model = 103
	Modelncep_nam_conus                        Model = 104
	Modelicon_d2_ruc                           Model = 105
	Modelecmwf_seas5                           Model = 106
	Modelecmwf_ec46                            Model = 107
	Modelecmwf_seasonal_seamless               Model = 108
	Modelecmwf_ifs_seamless                    Model = 109
	Modeljma_jaxa_mtg_fci                      Model = 110
	Modelgem_hrdps_west                        Model = 111
	Modelecmwf_wam                             Model = 112
	Modelncep_aigfs025                         Model = 113
	Modelncep_aigefs025                        Model = 114
	Modelncep_hgefs025_ensemble_mean           Model = 115
	Modelecmwf_seasonal_ensemble_mean_seamless Model = 116
	Modelecmwf_seas5_ensemble_mean             Model = 117
	Modelecmwf_ec46_ensemble_mean              Model = 118
	Modelncep_aigefs025_ensemble_mean          Model = 119
	Modeldwd_icon_eps_ensemble_mean_seamless   Model = 120
	Modeldwd_icon_eps_ensemble_mean            Model = 121
	Modeldwd_icon_eu_eps_ensemble_mean         Model = 122
	Modeldwd_icon_d2_eps_ensemble_mean         Model = 123
	Modelncep_gefs_ensemble_mean_seamless      Model = 124
	Modelncep_gefs025_ensemble_mean            Model = 125
	Modelncep_gefs05_ensemble_mean             Model = 126
	Modelecmwf_ifs025_ensemble_mean            Model = 127
	Modelecmwf_aifs025_ensemble_mean           Model = 128
	Modelmeteoswiss_icon_ch1_ensemble_mean     Model = 129
	Modelmeteoswiss_icon_ch2_ensemble_mean     Model = 130
	Modelcmc_gem_geps_ensemble_mean            Model = 131
	Modelukmo_global_ensemble_mean_20km        Model = 132
	Modelukmo_uk_ensemble_mean_2km             Model = 133
	Modeldwd_sis_europe_africa_v4              Model = 134
	Modelbom_access_global_ensemble_mean       Model = 135
	Modelecmwf_wam025_ensemble_mean            Model = 136
	Modelncep_gefswave025_ensemble_mean        Model = 137
	Modelgeosphere_arome_austria               Model = 138
)

var EnumNamesModel = map[Model]string{
	Modelundefined:                             "undefined",
	Modelbest_match:                            "best_match",
	Modelgfs_seamless:                          "gfs_seamless",
	Modelgfs_global:                            "gfs_global",
	Modelgfs_hrrr:                              "gfs_hrrr",
	Modelmeteofrance_seamless:                  "meteofrance_seamless",
	Modelmeteofrance_arpege_seamless:           "meteofrance_arpege_seamless",
	Modelmeteofrance_arpege_world:              "meteofrance_arpege_world",
	Modelmeteofrance_arpege_europe:             "meteofrance_arpege_europe",
	Modelmeteofrance_arome_seamless:            "meteofrance_arome_seamless",
	Modelmeteofrance_arome_france:              "meteofrance_arome_france",
	Modelmeteofrance_arome_france_hd:           "meteofrance_arome_france_hd",
	Modeljma_seamless:                          "jma_seamless",
	Modeljma_msm:                               "jma_msm",
	Modeljms_gsm:                               "jms_gsm",
	Modeljma_gsm:                               "jma_gsm",
	Modelgem_seamless:                          "gem_seamless",
	Modelgem_global:                            "gem_global",
	Modelgem_regional:                          "gem_regional",
	Modelgem_hrdps_continental:                 "gem_hrdps_continental",
	Modelicon_seamless:                         "icon_seamless",
	Modelicon_global:                           "icon_global",
	Modelicon_eu:                               "icon_eu",
	Modelicon_d2:                               "icon_d2",
	Modelecmwf_ifs04:                           "ecmwf_ifs04",
	Modelmetno_nordic:                          "metno_nordic",
	Modelera5_seamless:                         "era5_seamless",
	Modelera5:                                  "era5",
	Modelcerra:                                 "cerra",
	Modelera5_land:                             "era5_land",
	Modelecmwf_ifs:                             "ecmwf_ifs",
	Modelgwam:                                  "gwam",
	Modelewam:                                  "ewam",
	Modelglofas_seamless_v3:                    "glofas_seamless_v3",
	Modelglofas_forecast_v3:                    "glofas_forecast_v3",
	Modelglofas_consolidated_v3:                "glofas_consolidated_v3",
	Modelglofas_seamless_v4:                    "glofas_seamless_v4",
	Modelglofas_forecast_v4:                    "glofas_forecast_v4",
	Modelglofas_consolidated_v4:                "glofas_consolidated_v4",
	Modelgfs025:                                "gfs025",
	Modelgfs05:                                 "gfs05",
	ModelCMCC_CM2_VHR4:                         "CMCC_CM2_VHR4",
	ModelFGOALS_f3_H_highresSST:                "FGOALS_f3_H_highresSST",
	ModelFGOALS_f3_H:                           "FGOALS_f3_H",
	ModelHiRAM_SIT_HR:                          "HiRAM_SIT_HR",
	ModelMRI_AGCM3_2_S:                         "MRI_AGCM3_2_S",
	ModelEC_Earth3P_HR:                         "EC_Earth3P_HR",
	ModelMPI_ESM1_2_XR:                         "MPI_ESM1_2_XR",
	ModelNICAM16_8S:                            "NICAM16_8S",
	Modelcams_europe:                           "cams_europe",
	Modelcams_global:                           "cams_global",
	Modelcfsv2:                                 "cfsv2",
	Modelera5_ocean:                            "era5_ocean",
	Modelcma_grapes_global:                     "cma_grapes_global",
	Modelbom_access_global:                     "bom_access_global",
	Modelbom_access_global_ensemble:            "bom_access_global_ensemble",
	Modelarpae_cosmo_seamless:                  "arpae_cosmo_seamless",
	Modelarpae_cosmo_2i:                        "arpae_cosmo_2i",
	Modelarpae_cosmo_2i_ruc:                    "arpae_cosmo_2i_ruc",
	Modelarpae_cosmo_5m:                        "arpae_cosmo_5m",
	Modelecmwf_ifs025:                          "ecmwf_ifs025",
	Modelecmwf_aifs025:                         "ecmwf_aifs025",
	Modelgfs013:                                "gfs013",
	Modelgfs_graphcast025:                      "gfs_graphcast025",
	Modelecmwf_wam025:                          "ecmwf_wam025",
	Modelmeteofrance_wave:                      "meteofrance_wave",
	Modelmeteofrance_currents:                  "meteofrance_currents",
	Modelecmwf_wam025_ensemble:                 "ecmwf_wam025_ensemble",
	Modelncep_gfswave025:                       "ncep_gfswave025",
	Modelncep_gefswave025:                      "ncep_gefswave025",
	Modelknmi_seamless:                         "knmi_seamless",
	Modelknmi_harmonie_arome_europe:            "knmi_harmonie_arome_europe",
	Modelknmi_harmonie_arome_netherlands:       "knmi_harmonie_arome_netherlands",
	Modeldmi_seamless:                          "dmi_seamless",
	Modeldmi_harmonie_arome_europe:             "dmi_harmonie_arome_europe",
	Modelmetno_seamless:                        "metno_seamless",
	Modelera5_ensemble:                         "era5_ensemble",
	Modelecmwf_ifs_analysis:                    "ecmwf_ifs_analysis",
	Modelecmwf_ifs_long_window:                 "ecmwf_ifs_long_window",
	Modelecmwf_ifs_analysis_long_window:        "ecmwf_ifs_analysis_long_window",
	Modelukmo_global_deterministic_10km:        "ukmo_global_deterministic_10km",
	Modelukmo_uk_deterministic_2km:             "ukmo_uk_deterministic_2km",
	Modelukmo_seamless:                         "ukmo_seamless",
	Modelncep_gfswave016:                       "ncep_gfswave016",
	Modelncep_nbm_conus:                        "ncep_nbm_conus",
	Modelukmo_global_ensemble_20km:             "ukmo_global_ensemble_20km",
	Modelecmwf_aifs025_single:                  "ecmwf_aifs025_single",
	Modeljma_jaxa_himawari:                     "jma_jaxa_himawari",
	Modeleumetsat_sarah3:                       "eumetsat_sarah3",
	Modeleumetsat_lsa_saf_msg:                  "eumetsat_lsa_saf_msg",
	Modeleumetsat_lsa_saf_iodc:                 "eumetsat_lsa_saf_iodc",
	Modelsatellite_radiation_seamless:          "satellite_radiation_seamless",
	Modelkma_gdps:                              "kma_gdps",
	Modelkma_ldps:                              "kma_ldps",
	Modelkma_seamless:                          "kma_seamless",
	Modelitalia_meteo_arpae_icon_2i:            "italia_meteo_arpae_icon_2i",
	Modelukmo_uk_ensemble_2km:                  "ukmo_uk_ensemble_2km",
	Modelmeteofrance_arome_france_hd_15min:     "meteofrance_arome_france_hd_15min",
	Modelmeteofrance_arome_france_15min:        "meteofrance_arome_france_15min",
	Modelmeteoswiss_icon_ch1:                   "meteoswiss_icon_ch1",
	Modelmeteoswiss_icon_ch2:                   "meteoswiss_icon_ch2",
	Modelmeteoswiss_icon_ch1_ensemble:          "meteoswiss_icon_ch1_ensemble",
	Modelmeteoswiss_icon_ch2_ensemble:          "meteoswiss_icon_ch2_ensemble",
	Modelmeteoswiss_icon_seamless:              "meteoswiss_icon_seamless",
	Modelncep_nam_conus:                        "ncep_nam_conus",
	Modelicon_d2_ruc:                           "icon_d2_ruc",
	Modelecmwf_seas5:                           "ecmwf_seas5",
	Modelecmwf_ec46:                            "ecmwf_ec46",
	Modelecmwf_seasonal_seamless:               "ecmwf_seasonal_seamless",
	Modelecmwf_ifs_seamless:                    "ecmwf_ifs_seamless",
	Modeljma_jaxa_mtg_fci:                      "jma_jaxa_mtg_fci",
	Modelgem_hrdps_west:                        "gem_hrdps_west",
	Modelecmwf_wam:                             "ecmwf_wam",
	Modelncep_aigfs025:                         "ncep_aigfs025",
	Modelncep_aigefs025:                        "ncep_aigefs025",
	Modelncep_hgefs025_ensemble_mean:           "ncep_hgefs025_ensemble_mean",
	Modelecmwf_seasonal_ensemble_mean_seamless: "ecmwf_seasonal_ensemble_mean_seamless",
	Modelecmwf_seas5_ensemble_mean:             "ecmwf_seas5_ensemble_mean",
	Modelecmwf_ec46_ensemble_mean:              "ecmwf_ec46_ensemble_mean",
	Modelncep_aigefs025_ensemble_mean:          "ncep_aigefs025_ensemble_mean",
	Modeldwd_icon_eps_ensemble_mean_seamless:   "dwd_icon_eps_ensemble_mean_seamless",
	Modeldwd_icon_eps_ensemble_mean:            "dwd_icon_eps_ensemble_mean",
	Modeldwd_icon_eu_eps_ensemble_mean:         "dwd_icon_eu_eps_ensemble_mean",
	Modeldwd_icon_d2_eps_ensemble_mean:         "dwd_icon_d2_eps_ensemble_mean",
	Modelncep_gefs_ensemble_mean_seamless:      "ncep_gefs_ensemble_mean_seamless",
	Modelncep_gefs025_ensemble_mean:            "ncep_gefs025_ensemble_mean",
	Modelncep_gefs05_ensemble_mean:             "ncep_gefs05_ensemble_mean",
	Modelecmwf_ifs025_ensemble_mean:            "ecmwf_ifs025_ensemble_mean",
	Modelecmwf_aifs025_ensemble_mean:           "ecmwf_aifs025_ensemble_mean",
	Modelmeteoswiss_icon_ch1_ensemble_mean:     "meteoswiss_icon_ch1_ensemble_mean",
	Modelmeteoswiss_icon_ch2_ensemble_mean:     "meteoswiss_icon_ch2_ensemble_mean",
	Modelcmc_gem_geps_ensemble_mean:            "cmc_gem_geps_ensemble_mean",
	Modelukmo_global_ensemble_mean_20km:        "ukmo_global_ensemble_mean_20km",
	Modelukmo_uk_ensemble_mean_2km:             "ukmo_uk_ensemble_mean_2km",
	Modeldwd_sis_europe_africa_v4:              "dwd_sis_europe_africa_v4",
	Modelbom_access_global_ensemble_mean:       "bom_access_global_ensemble_mean",
	Modelecmwf_wam025_ensemble_mean:            "ecmwf_wam025_ensemble_mean",
	Modelncep_gefswave025_ensemble_mean:        "ncep_gefswave025_ensemble_mean",
	Modelgeosphere_arome_austria:               "geosphere_arome_austria",
}

var EnumValuesModel = map[string]Model{
	"undefined":                             Modelundefined,
	"best_match":                            Modelbest_match,
	"gfs_seamless":                          Modelgfs_seamless,
	"gfs_global":                            Modelgfs_global,
	"gfs_hrrr":                              Modelgfs_hrrr,
	"meteofrance_seamless":                  Modelmeteofrance_seamless,
	"meteofrance_arpege_seamless":           Modelmeteofrance_arpege_seamless,
	"meteofrance_arpege_world":              Modelmeteofrance_arpege_world,
	"meteofrance_arpege_europe":             Modelmeteofrance_arpege_europe,
	"meteofrance_arome_seamless":            Modelmeteofrance_arome_seamless,
	"meteofrance_arome_france":              Modelmeteofrance_arome_france,
	"meteofrance_arome_france_hd":           Modelmeteofrance_arome_france_hd,
	"jma_seamless":                          Modeljma_seamless,
	"jma_msm":                               Modeljma_msm,
	"jms_gsm":                               Modeljms_gsm,
	"jma_gsm":                               Modeljma_gsm,
	"gem_seamless":                          Modelgem_seamless,
	"gem_global":                            Modelgem_global,
	"gem_regional":                          Modelgem_regional,
	"gem_hrdps_continental":                 Modelgem_hrdps_continental,
	"icon_seamless":                         Modelicon_seamless,
	"icon_global":                           Modelicon_global,
	"icon_eu":                               Modelicon_eu,
	"icon_d2":                               Modelicon_d2,
	"ecmwf_ifs04":                           Modelecmwf_ifs04,
	"metno_nordic":                          Modelmetno_nordic,
	"era5_seamless":                         Modelera5_seamless,
	"era5":                                  Modelera5,
	"cerra":                                 Modelcerra,
	"era5_land":                             Modelera5_land,
	"ecmwf_ifs":                             Modelecmwf_ifs,
	"gwam":                                  Modelgwam,
	"ewam":                                  Modelewam,
	"glofas_seamless_v3":                    Modelglofas_seamless_v3,
	"glofas_forecast_v3":                    Modelglofas_forecast_v3,
	"glofas_consolidated_v3":                Modelglofas_consolidated_v3,
	"glofas_seamless_v4":                    Modelglofas_seamless_v4,
	"glofas_forecast_v4":                    Modelglofas_forecast_v4,
	"glofas_consolidated_v4":                Modelglofas_consolidated_v4,
	"gfs025":                                Modelgfs025,
	"gfs05":                                 Modelgfs05,
	"CMCC_CM2_VHR4":                         ModelCMCC_CM2_VHR4,
	"FGOALS_f3_H_highresSST":                ModelFGOALS_f3_H_highresSST,
	"FGOALS_f3_H":                           ModelFGOALS_f3_H,
	"HiRAM_SIT_HR":                          ModelHiRAM_SIT_HR,
	"MRI_AGCM3_2_S":                         ModelMRI_AGCM3_2_S,
	"EC_Earth3P_HR":                         ModelEC_Earth3P_HR,
	"MPI_ESM1_2_XR":                         ModelMPI_ESM1_2_XR,
	"NICAM16_8S":                            ModelNICAM16_8S,
	"cams_europe":                           Modelcams_europe,
	"cams_global":                           Modelcams_global,
	"cfsv2":                                 Modelcfsv2,
	"era5_ocean":                            Modelera5_ocean,
	"cma_grapes_global":                     Modelcma_grapes_global,
	"bom_access_global":                     Modelbom_access_global,
	"bom_access_global_ensemble":            Modelbom_access_global_ensemble,
	"arpae_cosmo_seamless":                  Modelarpae_cosmo_seamless,
	"arpae_cosmo_2i":                        Modelarpae_cosmo_2i,
	"arpae_cosmo_2i_ruc":                    Modelarpae_cosmo_2i_ruc,
	"arpae_cosmo_5m":                        Modelarpae_cosmo_5m,
	"ecmwf_ifs025":                          Modelecmwf_ifs025,
	"ecmwf_aifs025":                         Modelecmwf_aifs025,
	"gfs013":                                Modelgfs013,
	"gfs_graphcast025":                      Modelgfs_graphcast025,
	"ecmwf_wam025":                          Modelecmwf_wam025,
	"meteofrance_wave":                      Modelmeteofrance_wave,
	"meteofrance_currents":                  Modelmeteofrance_currents,
	"ecmwf_wam025_ensemble":                 Modelecmwf_wam025_ensemble,
	"ncep_gfswave025":                       Modelncep_gfswave025,
	"ncep_gefswave025":                      Modelncep_gefswave025,
	"knmi_seamless":                         Modelknmi_seamless,
	"knmi_harmonie_arome_europe":            Modelknmi_harmonie_arome_europe,
	"knmi_harmonie_arome_netherlands":       Modelknmi_harmonie_arome_netherlands,
	"dmi_seamless":                          Modeldmi_seamless,
	"dmi_harmonie_arome_europe":             Modeldmi_harmonie_arome_europe,
	"metno_seamless":                        Modelmetno_seamless,
	"era5_ensemble":                         Modelera5_ensemble,
	"ecmwf_ifs_analysis":                    Modelecmwf_ifs_analysis,
	"ecmwf_ifs_long_window":                 Modelecmwf_ifs_long_window,
	"ecmwf_ifs_analysis_long_window":        Modelecmwf_ifs_analysis_long_window,
	"ukmo_global_deterministic_10km":        Modelukmo_global_deterministic_10km,
	"ukmo_uk_deterministic_2km":             Modelukmo_uk_deterministic_2km,
	"ukmo_seamless":                         Modelukmo_seamless,
	"ncep_gfswave016":                       Modelncep_gfswave016,
	"ncep_nbm_conus":                        Modelncep_nbm_conus,
	"ukmo_global_ensemble_20km":             Modelukmo_global_ensemble_20km,
	"ecmwf_aifs025_single":                  Modelecmwf_aifs025_single,
	"jma_jaxa_himawari":                     Modeljma_jaxa_himawari,
	"eumetsat_sarah3":                       Modeleumetsat_sarah3,
	"eumetsat_lsa_saf_msg":                  Modeleumetsat_lsa_saf_msg,
	"eumetsat_lsa_saf_iodc":                 Modeleumetsat_lsa_saf_iodc,
	"satellite_radiation_seamless":          Modelsatellite_radiation_seamless,
	"kma_gdps":                              Modelkma_gdps,
	"kma_ldps":                              Modelkma_ldps,
	"kma_seamless":                          Modelkma_seamless,
	"italia_meteo_arpae_icon_2i":            Modelitalia_meteo_arpae_icon_2i,
	"ukmo_uk_ensemble_2km":                  Modelukmo_uk_ensemble_2km,
	"meteofrance_arome_france_hd_15min":     Modelmeteofrance_arome_france_hd_15min,
	"meteofrance_arome_france_15min":        Modelmeteofrance_arome_france_15min,
	"meteoswiss_icon_ch1":                   Modelmeteoswiss_icon_ch1,
	"meteoswiss_icon_ch2":                   Modelmeteoswiss_icon_ch2,
	"meteoswiss_icon_ch1_ensemble":          Modelmeteoswiss_icon_ch1_ensemble,
	"meteoswiss_icon_ch2_ensemble":          Modelmeteoswiss_icon_ch2_ensemble,
	"meteoswiss_icon_seamless":              Modelmeteoswiss_icon_seamless,
	"ncep_nam_conus":                        Modelncep_nam_conus,
	"icon_d2_ruc":                           Modelicon_d2_ruc,
	"ecmwf_seas5":                           Modelecmwf_seas5,
	"ecmwf_ec46":                            Modelecmwf_ec46,
	"ecmwf_seasonal_seamless":               Modelecmwf_seasonal_seamless,
	"ecmwf_ifs_seamless":                    Modelecmwf_ifs_seamless,
	"jma_jaxa_mtg_fci":                      Modeljma_jaxa_mtg_fci,
	"gem_hrdps_west":                        Modelgem_hrdps_west,
	"ecmwf_wam":                             Modelecmwf_wam,
	"ncep_aigfs025":                         Modelncep_aigfs025,
	"ncep_aigefs025":                        Modelncep_aigefs025,
	"ncep_hgefs025_ensemble_mean":           Modelncep_hgefs025_ensemble_mean,
	"ecmwf_seasonal_ensemble_mean_seamless": Modelecmwf_seasonal_ensemble_mean_seamless,
	"ecmwf_seas5_ensemble_mean":             Modelecmwf_seas5_ensemble_mean,
	"ecmwf_ec46_ensemble_mean":              Modelecmwf_ec46_ensemble_mean,
	"ncep_aigefs025_ensemble_mean":          Modelncep_aigefs025_ensemble_mean,
	"dwd_icon_eps_ensemble_mean_seamless":   Modeldwd_icon_eps_ensemble_mean_seamless,
	"dwd_icon_eps_ensemble_mean":            Modeldwd_icon_eps_ensemble_mean,
	"dwd_icon_eu_eps_ensemble_mean":         Modeldwd_icon_eu_eps_ensemble_mean,
	"dwd_icon_d2_eps_ensemble_mean":         Modeldwd_icon_d2_eps_ensemble_mean,
	"ncep_gefs_ensemble_mean_seamless":      Modelncep_gefs_ensemble_mean_seamless,
	"ncep_gefs025_ensemble_mean":            Modelncep_gefs025_ensemble_mean,
	"ncep_gefs05_ensemble_mean":             Modelncep_gefs05_ensemble_mean,
	"ecmwf_ifs025_ensemble_mean":            Modelecmwf_ifs025_ensemble_mean,
	"ecmwf_aifs025_ensemble_mean":           Modelecmwf_aifs025_ensemble_mean,
	"meteoswiss_icon_ch1_ensemble_mean":     Modelmeteoswiss_icon_ch1_ensemble_mean,
	"meteoswiss_icon_ch2_ensemble_mean":     Modelmeteoswiss_icon_ch2_ensemble_mean,
	"cmc_gem_geps_ensemble_mean":            Modelcmc_gem_geps_ensemble_mean,
	"ukmo_global_ensemble_mean_20km":        Modelukmo_global_ensemble_mean_20km,
	"ukmo_uk_ensemble_mean_2km":             Modelukmo_uk_ensemble_mean_2km,
	"dwd_sis_europe_africa_v4":              Modeldwd_sis_europe_africa_v4,
	"bom_access_global_ensemble_mean":       Modelbom_access_global_ensemble_mean,
	"ecmwf_wam025_ensemble_mean":            Modelecmwf_wam025_ensemble_mean,
	"ncep_gefswave025_ensemble_mean":        Modelncep_gefswave025_ensemble_mean,
	"geosphere_arome_austria":               Modelgeosphere_arome_austria,
}

func (v Model) String() string {
	if s, ok := EnumNamesModel[v]; ok {
		return s
	}
	return "Model(" + strconv.FormatInt(int64(v), 10) + ")"
}
