// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package openmeteo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VariablesWithMonth struct {
	_tab flatbuffers.Table
}

func GetRootAsVariablesWithMonth(buf []byte, offset flatbuffers.UOffsetT) *VariablesWithMonth {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VariablesWithMonth{}
	x.Init(buf, n+offset)
	return x
}

func FinishVariablesWithMonthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVariablesWithMonth(buf []byte, offset flatbuffers.UOffsetT) *VariablesWithMonth {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VariablesWithMonth{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVariablesWithMonthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VariablesWithMonth) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VariablesWithMonth) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VariablesWithMonth) Year() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithMonth) MutateYear(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *VariablesWithMonth) Month() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithMonth) MutateMonth(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func (rcv *VariablesWithMonth) Count() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithMonth) MutateCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *VariablesWithMonth) Variables(obj *VariableWithValues, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VariablesWithMonth) VariablesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func VariablesWithMonthStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func VariablesWithMonthAddYear(builder *flatbuffers.Builder, year int16) {
	builder.PrependInt16Slot(0, year, 0)
}
func VariablesWithMonthAddMonth(builder *flatbuffers.Builder, month int8) {
	builder.PrependInt8Slot(1, month, 0)
}
func VariablesWithMonthAddCount(builder *flatbuffers.Builder, count int32) {
	builder.PrependInt32Slot(2, count, 0)
}
func VariablesWithMonthAddVariables(builder *flatbuffers.Builder, variables flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(variables), 0)
}
func VariablesWithMonthStartVariablesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VariablesWithMonthEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
